/* eslint-disable @typescript-eslint/no-unused-expressions */
import React from 'react';
import Header from '../Header/Header';
import Footer from '../Footer/Footer';
import Head from 'next/head';
import CheckAuth from './CheckAuth';
// import { Inter } from '@next/font/google';

// const inter = Inter({ subsets: ['latin'] });

const Main = ({ children }: any) => {
 
  return (
    <>
      <Head>
        <title>Akuntansi One</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CheckAuth>
        <div className="wrapper">
          <Header />
          {children}
          <Footer />
        </div>
      </CheckAuth>
    </>
  );
};

export default Main;