import React from 'react'
import { Inter } from '@next/font/google'
import Header from '../Header/Header'
import Footer from '../Footer/Footer'
import { Layout, Space } from 'antd';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] })

const Main = ({children}: any) => {
  return (
    <>
      <Head>
        <title>Akuntansi One</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Space direction="vertical" style={{ width: '100%' }} size={[0, 48]}> */}
      <Space direction="vertical" style={{ width: '100%' }} size={[0, 0]}>
        <Layout>
          <div className="wrapper">
            <Header />
            {children}
            <Footer />
          </div>
        </Layout>
      </Space>
    </>
  )
}

export default Main